POST https://anthonysjhenry.com/api/auth
Content-Type: application/json

{
    "email": "admin@example.com",
    "username": "admin",
    "password": "antmin",
    "first_name": "Admin",
    "last_name": "Admin",
    "role": "admin",
    "role_secret": "f6b455b54fde8f9976820a16161a52f69b4a3da35d34bb721ed95097f7ccc73f"
}
