POST https://localhost:4000/todos
Accept-Encoding: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlcjEiLCJpZCI6NCwiZXhwIjoxNzczOTg5MzYyfQ.7dIcs7FqzM3408UFPu0dUmLXmP65kz761kgILVFNKVI
Content-Type: application/json

{
    "title": "Talk to a stranger",
    "description": "be social",
    "priority": 1,
    "completed": false
}