POST https://localhost:4000/auth
Content-Type: application/json

{
    "email": "test1@example.com",
    "username": "testuser1",
    "password": "password123",
    "first_name": "Test",
    "last_name": "User",
    "role": "user"
}
